Add tests to check for obviously missing components
packethost/packet-hardware pull request #73
Opened 2024-05-15 18:06 UTC by ofaurax

2024-05-17 12:39 UTC, splaspood requested changes
This looks good...  we should probably also add some test to validate the integer vs string issue we had previously.

2024-05-17 12:39 UTC, splaspood commented on .github/workflows/ci.yaml
> +          - ubuntu-20.04
It's no longer used, but packet-hardware was run under ubuntu 16.04 for most of its life..  maybe we should continue testing against that?   (maybe not..)

2024-05-20 17:24 UTC, iancoffey commented on .github/workflows/ci.yaml
> +          jq -e '.[] | select(.component_type == "ProcessorComponent")' cache.json
Would these be better in a file we can we +x instead of inline?

2024-05-21 11:39 UTC, ofaurax commented on .github/workflows/ci.yaml
> +          - ubuntu-20.04
I tried to test against "all available" so that we are covered for everything that's available.

If we should restrict on ubuntu versions or even python versions, we should also add a not on the README.

2024-05-21 11:45 UTC, ofaurax commented on .github/workflows/ci.yaml
> +          jq -e '.[] | select(.component_type == "ProcessorComponent")' cache.json
You want to put the output of this command in a file rather that display it in CI traces?
I find it faster to directly have the traces right there when the CI fails.
Or perhaps you mean the cache.json should be provided as an artifact?

2024-05-23 01:01 UTC, iancoffey commented on .github/workflows/ci.yaml
> +          jq -e '.[] | select(.component_type == "ProcessorComponent")' cache.json
> I find it faster to directly have the traces right there when the CI fails.

Sure, just saying I wish we could run these same validation other ways. No big deal, dont block this.

2024-05-23 09:45 UTC, ofaurax commented
> This looks good... we should probably also add some test to validate the integer vs string issue we had previously.

Is this what blocks this PR?

2024-05-24 12:08 UTC, splaspood approved these changes

2024-05-24 13:52 UTC, merged